---
abstract: 'capture all constructor errors'
author:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200005, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Constructor-AllErrors
requires:
  Moose: 1.04
  Test::Fatal: 0
  Test::More: 0
version: 0.014
