--- 
abstract: capture all constructor errors
author: 
  - Hans Dieter Pearcey <hdp@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: MooseX-Constructor-AllErrors
requires: 
  Moose: 0.65
  Test::More: 0
version: 0.007
